# WebSocket服务器配置

# 服务器端口
port: 8081

# 数据库配置
db_host: "127.0.0.1" # 数据库主机
db_port: 3308 # 数据库端口
db_username: "root" # 数据库用户名
db_password: "root" # 数据库密码
db_name: "phone_db" # 数据库名称

# AI服务配置
ai_api_key: "********"
ai_base_url: "********"
ai_model: "********"
thinking: "disabled"

# 日志配置
log_level: "INFO" # 日志级别：DEBUG/INFO/WARN/ERROR/FATAL
log_file_path: "logs/" # 日志文件路径
log_max_size: 100 # 日志文件最大大小（MB）
log_max_days: 7 # 日志文件保留天数
log_compress: false # 是否压缩日志文件
log_console_server: true # 是否将基本日志信息输出到控制台
log_console_database: false # 是否将数据库操作日志信息输出到控制台
